### ISSUE TITLE
Error while using 'Dream Video'

### ISSUE THREAD

**Issue by vihansolo** [kenjibailly/Deep_Dream_GUI#2]
Hello, I've been trying to use this software to create dream videos, everything else I've tried is working well but when it comes to converting videos to 'dream videos', I am getting this error after it has achieved 2 levels of recursion -

Starting Deep Dream with chosen parameters:
Layer = 7
Iterations = 25
Recursive Level = 2
------------------------------------------------------

Recursive level: 0
Processing image:
. . . . . . . . . . . . . . . . . . . . . . . . . 
Recursive level: 1
Processing image:
. . . . . . . . . . . . . . . . . . . . . . . . . 
Recursive level: 2
Processing image:
Traceback (most recent call last):
  File "X:\Work\Projects\Python Projects\Deep Dream\Deep_Dream_GUI\backend\src\py\windows\sub_menu_one_template.py", line 362, in <lambda>
    self.button_generate.clicked.connect(lambda: window_callback.clicked('generate', MainWindow, self))
  File "X:\Work\Projects\Python Projects\Deep Dream\Deep_Dream_GUI\backend\src\py\windows\dream_video_window.py", line 77, in clicked
    dream_video.start_dream_video(input_layer, input_iterations, input_recursive_level, input_file, output_folder, self)
  File "X:\Work\Projects\Python Projects\Deep Dream\Deep_Dream_GUI\backend\src\py\main_functions\dream_video.py", line 62, in start_dream_video
    dream_video_start.initiate_start(deep_dream_frames_folder, input_layer, iterations, recursive_level, input_folder, output_folder, self)
  File "X:\Work\Projects\Python Projects\Deep Dream\Deep_Dream_GUI\backend\src\py\functions\dream_video_start.py", line 85, in initiate_start
    start_deep_dream.start_deep_dream(deep_dream_frames_folder, fps, layer_tensor, input_layer, iterations, recursive_level, last_index, total_frames, output_folder, self)
  File "X:\Work\Projects\Python Projects\Deep Dream\Deep_Dream_GUI\backend\src\py\functions\start_deep_dream.py", line 100, in start_deep_dream
    self.progress.setValue(self.completed)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by vihansolo** [comment]
I did try commenting this part of the code -

Progress bar, 80 because 10 init and 10 end
self.completed += 80/files_length
self.progress.setValue(self.completed)

And the frames are being saved as of now
